### ISSUE TITLE
Unable to send - Gmail OAuth

### ISSUE THREAD

**Issue by mattsnowboard** [bokysan/docker-postfix#117]
I'm trying to setup postfix to send email through Gmail using OAuth (now that the insecure method is not allowed). But I have not been able to get it to work.

My docker compose:

```
version: "3.9"

networks:
  default:
    driver: bridge
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

secrets:
  postfix_xoauth_client_id:
    file: $DOCKERDIR/secrets/postfix_xoauth_client_id
  postfix_xoauth_secret:
    file: $DOCKERDIR/secrets/postfix_xoauth_secret
  postfix_initial_access_token:
    file: $DOCKERDIR/secrets/postfix_initial_access_token
  postfix_initial_refresh_token:
    file: $DOCKERDIR/secrets/postfix_initial_refresh_token

services:

  # Postfix Email for sending via Gmail
  postfix:
    image: boky/postfix:latest
    container_name: postfix
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    ports:
      - "$POSTFIX_PORT:587"
    environment:
      - TZ=$TZ
      - RELAYHOST=[smtp.gmail.com]:587
      - RELAYHOST_USERNAME=$GMAIL_ACCOUNT
      - POSTFIX_smtp_tls_security_level=encrypt
      - ALLOW_EMPTY_SENDER_DOMAINS=true
      - XOAUTH2_SYSLOG_ON_FAILURE=yes
      - XOAUTH2_FULL_TRACE=yes
      - XOAUTH2_CLIENT_ID_FILE=/run/secrets/postfix_xoauth_client_id
      - XOAUTH2_SECRET_FILE=/run/secrets/postfix_xoauth_secret
      - XOAUTH2_INITIAL_ACCESS_TOKEN_FILE=/run/secrets/postfix_initial_access_token
      - XOAUTH2_INITIAL_REFRESH_TOKEN_FILE=/run/secrets/postfix_initial_refresh_token
    secrets:
      - postfix_xoauth_client_id
      - postfix_xoauth_secret
      - postfix_initial_access_token
      - postfix_initial_refresh_token
    volumes:
      #- $DOCKERDIR/appdata/postfix:/var/spool/postfix # manually create email@domain token file...
```

When I try to send mail from the container, I noticed that the token file that should be created is missing:

```
matt@srv2:~/docker$ docker exec -it postfix /bin/bash
bash-5.1# ls -la /var/spool/postfix/xoauth2-tokens/
total 8
drwxr-xr-x    2 postfix  root          4096 Nov  7 08:34 .
drwxr-xr-x   18 root     root          4096 Nov  7 08:34 ..
bash-5.1# echo "test" | sendmail <redacted>@<redacted>
```

And the logs show that is the reason it fails

```
11/07/2022 8:34:24 AM ????? POSTFIX STARTING UP ?????
11/07/2022 8:34:24 AM NOTE  Setting container timezone to: America/Los_Angeles
11/07/2022 8:34:24 AM INFO  Using plain log format for rsyslog.
11/07/2022 8:34:24 AM NOTE  Emails in the logs will not be anonymized. Set ANONYMIZE_EMAILS to enable this feature.
11/07/2022 8:34:24 AM DEBUG Reowing root: /var/spool/postfix/
11/07/2022 8:34:24 AM DEBUG Reowing root: /var/spool/postfix/pid/
11/07/2022 8:34:24 AM DEBUG Reowing postfix:postdrop /var/spool/postfix/private/
11/07/2022 8:34:24 AM DEBUG Reowing postfix:postdrop /var/spool/postfix/public/
11/07/2022 8:34:26 AM DEBUG No upgrade needed.
11/07/2022 8:34:28 AM INFO  Using unlimited message size.
11/07/2022 8:34:28 AM NOTE  Forwarding all emails to [smtp.gmail.com]:587 using username ******@gmail.com and password (redacted).
11/07/2022 8:34:30 AM INFO  Using default private network list for trusted networks.
11/07/2022 8:34:30 AM INFO  Debugging is disabled.
11/07/2022 8:34:30 AM DEBUG DKIM_AUTOGENERATE not set -- you will need to provide your own keys.
11/07/2022 8:34:30 AM INFO  No DKIM keys found, will not use DKIM.
11/07/2022 8:34:30 AM INFO  Applying custom postfix setting: message_size_limit=0
11/07/2022 8:34:30 AM INFO  Applying custom postfix setting: myhostname=7620e44162f9
11/07/2022 8:34:30 AM INFO  Applying custom postfix setting: mynetworks=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
11/07/2022 8:34:30 AM INFO  Applying custom postfix setting: smtp_tls_security_level=encrypt
11/07/2022 8:34:30 AM NOTE  Starting: rsyslog, postfix
11/07/2022 8:34:30 AM 2022-11-07 08:34:30,828 INFO Set uid to user 0 succeeded
11/07/2022 8:34:30 AM 2022-11-07 08:34:30,829 INFO supervisord started with pid 1
11/07/2022 8:34:31 AM 2022-11-07 08:34:31,833 INFO spawned: 'opendkim' with pid 119
11/07/2022 8:34:31 AM 2022-11-07 08:34:31,837 INFO spawned: 'postfix' with pid 120
11/07/2022 8:34:31 AM 2022-11-07 08:34:31,837 INFO spawned: 'rsyslog' with pid 121
11/07/2022 8:34:31 AM 2022-11-07T08:34:31.840309-08:00 INFO    : [origin software="rsyslogd" swVersion="8.2204.1" x-pid="121" x-info="https://www.rsyslog.com"] start
11/07/2022 8:34:31 AM 2022-11-07 08:34:31,840 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
11/07/2022 8:34:32 AM 2022-11-07T08:34:32.657816-08:00 INFO    postfix/postfix-script[191]: starting the Postfix mail system
11/07/2022 8:34:32 AM 2022-11-07T08:34:32.661107-08:00 INFO    postfix/master[192]: daemon started -- version 3.7.2, configuration /etc/postfix
11/07/2022 8:34:34 AM 2022-11-07 08:34:34,663 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
11/07/2022 8:34:37 AM 2022-11-07 08:34:37,668 INFO success: opendkim entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.636702-08:00 INFO    postfix/pickup[193]: 9B6D6C83CA: uid=0 from=<root>
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.638820-08:00 INFO    postfix/cleanup[225]: 9B6D6C83CA: message-id=<20221107163552.9B6D6C83CA@7620e44162f9>
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.640099-08:00 INFO    postfix/qmgr[194]: 9B6D6C83CA: from=<root@7620e44162f9>, size=246, nrcpt=1 (queue active)
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.898414-08:00 INFO    postfix/smtp[227]: 9B6D6C83CA: to=<redacted@redacted>, relay=smtp.gmail.com[172.253.117.108]:587, delay=0.26, delays=0.02/0.01/0.23/0, dsn=4.7.0, status=deferred (SASL authentication failed; cannot authenticate to server smtp.gmail.com[172.253.117.108]: generic failure)
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.898784-08:00 WARNING sasl-xoauth2: auth failed:
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.898809-08:00 WARNING sasl-xoauth2:   2022-11-07 08:35:52: Client: created
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.898825-08:00 WARNING sasl-xoauth2:   2022-11-07 08:35:52: Client::DoStep: called with state 0
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.898840-08:00 WARNING sasl-xoauth2:   2022-11-07 08:35:52: Client::InitialStep: TriggerAuthNameCallback err=0
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.898855-08:00 WARNING sasl-xoauth2:   2022-11-07 08:35:52: Client::InitialStep: TriggerPasswordCallback err=0
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.898871-08:00 WARNING sasl-xoauth2:   2022-11-07 08:35:52: TokenStore::Read: file=/var/spool/postfix/xoauth2-tokens/******@gmail.com
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.898886-08:00 WARNING sasl-xoauth2:   2022-11-07 08:35:52: TokenStore::Read: failed to open file /var/spool/postfix/xoauth2-tokens/******@gmail.com: No such file or directory
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.898902-08:00 WARNING sasl-xoauth2:   2022-11-07 08:35:52: Client::DoStep: new state 0 and err -1
11/07/2022 8:35:52 AM 2022-11-07T08:35:52.898917-08:00 WARNING sasl-xoauth2:   2022-11-07 08:35:52: Client: destroyed
```

So I manually created the file with the initial tokens I had retrieved and tried again, with this failure:

```
11/07/2022 12:07:52 AM ????? POSTFIX STARTING UP ?????
11/07/2022 12:07:52 AM NOTE  Setting container timezone to: America/Los_Angeles
11/07/2022 12:07:52 AM INFO  Using plain log format for rsyslog.
11/07/2022 12:07:52 AM NOTE  Emails in the logs will not be anonymized. Set ANONYMIZE_EMAILS to enable this feature.
11/07/2022 12:07:52 AM DEBUG Reowing root: /var/spool/postfix/
11/07/2022 12:07:52 AM DEBUG Reowing root: /var/spool/postfix/pid/
11/07/2022 12:07:52 AM DEBUG Reowing postfix:postdrop /var/spool/postfix/private/
11/07/2022 12:07:52 AM DEBUG Reowing postfix:postdrop /var/spool/postfix/public/
11/07/2022 12:07:54 AM DEBUG No upgrade needed.
11/07/2022 12:07:56 AM INFO  Using unlimited message size.
11/07/2022 12:07:56 AM NOTE  Forwarding all emails to [smtp.gmail.com]:587 using username ******@gmail.com and password (redacted).
11/07/2022 12:07:58 AM INFO  Using default private network list for trusted networks.
11/07/2022 12:07:58 AM INFO  Debugging is disabled.
11/07/2022 12:07:58 AM DEBUG DKIM_AUTOGENERATE not set -- you will need to provide your own keys.
11/07/2022 12:07:58 AM INFO  No DKIM keys found, will not use DKIM.
11/07/2022 12:07:58 AM INFO  Applying custom postfix setting: message_size_limit=0
11/07/2022 12:07:58 AM INFO  Applying custom postfix setting: myhostname=11383e6ad3ff
11/07/2022 12:07:58 AM INFO  Applying custom postfix setting: mynetworks=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
11/07/2022 12:07:58 AM INFO  Applying custom postfix setting: smtp_tls_security_level=encrypt
11/07/2022 12:07:58 AM NOTE  Starting: rsyslog, postfix
11/07/2022 12:07:58 AM 2022-11-07 00:07:58,655 INFO Set uid to user 0 succeeded
11/07/2022 12:07:58 AM 2022-11-07 00:07:58,657 INFO supervisord started with pid 1
11/07/2022 12:07:59 AM 2022-11-07 00:07:59,660 INFO spawned: 'opendkim' with pid 120
11/07/2022 12:07:59 AM 2022-11-07 00:07:59,664 INFO spawned: 'postfix' with pid 121
11/07/2022 12:07:59 AM 2022-11-07 00:07:59,665 INFO spawned: 'rsyslog' with pid 122
11/07/2022 12:07:59 AM 2022-11-07T00:07:59.667685-08:00 INFO    : [origin software="rsyslogd" swVersion="8.2204.1" x-pid="122" x-info="https://www.rsyslog.com"] start
11/07/2022 12:07:59 AM 2022-11-07 00:07:59,668 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
11/07/2022 12:08:00 AM 2022-11-07T00:08:00.847359-08:00 WARNING postfix/postfix-script[220]: warning: group or other writable: /var/spool/postfix/pid
11/07/2022 12:08:00 AM2022-11-07T00:08:00.852310-08:00 INFO    postfix/postfix-script[237]: starting the Postfix mail system
11/07/2022 12:08:00 AM 2022-11-07T00:08:00.854792-08:00 INFO    postfix/master[238]: daemon started -- version 3.7.2, configuration /etc/postfix
11/07/2022 12:08:01 AM 2022-11-07 00:08:01,856 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
11/07/2022 12:08:04 AM 2022-11-07 00:08:04,859 INFO success: opendkim entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
11/07/2022 12:08:48 AM 2022-11-07T00:08:48.527769-08:00 INFO    postfix/pickup[239]: 80D4D5F86E: uid=0 from=<root>
11/07/2022 12:08:48 AM 2022-11-07T00:08:48.529940-08:00 INFO    postfix/cleanup[260]: 80D4D5F86E: message-id=<20221107080848.80D4D5F86E@11383e6ad3ff>
11/07/2022 12:08:48 AM 2022-11-07T00:08:48.531747-08:00 INFO    postfix/qmgr[240]: 80D4D5F86E: from=<root@11383e6ad3ff>, size=253, nrcpt=1 (queue active)
11/07/2022 12:08:48 AM 2022-11-07T00:08:48.940693-08:00 WARNING postfix/qmgr[240]: warning: private/smtp socket: malformed response
11/07/2022 12:08:48 AM 2022-11-07T00:08:48.940736-08:00 WARNING postfix/qmgr[240]: warning: transport smtp failure -- see a previous warning/fatal/panic logfile record for the problem description
11/07/2022 12:08:48 AM 2022-11-07T00:08:48.940835-08:00 WARNING postfix/master[238]: warning: process /usr/libexec/postfix/smtp pid 262 killed by signal 11
11/07/2022 12:08:48 AM 2022-11-07T00:08:48.940855-08:00 WARNING postfix/master[238]: warning: /usr/libexec/postfix/smtp: bad command startup -- throttling
11/07/2022 12:08:48 AM 2022-11-07T00:08:48.951865-08:00 INFO    postfix/error[265]: 80D4D5F86E: to=<redacted@redacted>, relay=none, delay=0.44, delays=0.02/0.42/0/0, dsn=4.3.0, status=deferred (unknown mail transport error)
```

So it looks like it fails due to "malformed response" and I don't know what to look at next or what I'm doing wrong.

Host is Debian.
