### ISSUE TITLE
Setting container security context generates invalid YAML

### ISSUE THREAD

**Issue by mjohnson9** [bokysan/docker-postfix#118]
When `container.postfix.securityContext` is set in `values.yaml`, the template generates invalid YAML that looks like this snippet:
```yaml
      containers:
        - name: smtp
          image: "boky/postfix:v3.5.1"
          imagePullPolicy: IfNotPresent
          securityContext:            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          ports:
```
