### ISSUE TITLE
Specify log file for Prometheus exporter 

### ISSUE THREAD

**Issue by jonathon2nd** [bokysan/docker-postfix#119]
Hello!

I am attempting to setup to use [this](https://github.com/kumina/postfix_exporter/tree/master) as a sidecar for metrics. I have the side car working, and shared the `/var/spool/postfix` volume with it. The problem is it either expects to read a log file `--postfix.logfile_path`, or docker logs. I am running this in k8s, so the easist thing would be to have a log file shared.

However, no matter that I use I can not get a log file to be written. I looked at [this](https://github.com/bokysan/docker-postfix/issues/110), and tried the following for helm install. But I can not get any log file created. Am I missing something. 
```
  general:
    LOG_FORMAT: plain
    LOG_FILE: /var/log/mail.log
...
  postfix:
    LOG_FORMAT: plain
    LOG_FILE: /var/log/mail.log
```

Tried the following too, no effect.
```
extraEnv:
  - name: POSTFIX_FORCE_COLOR
    value: "1"
  - name: POSTFIX_INBOUND_DEBUGGING
    value: "0"
  - name: POSTFIX_LOG_FORMAT
    value: plain
  - name: POSTFIX_LOG_FILE
    value: "/var/log/mail.log"
```
