### ISSUE TITLE
[Need Help] How to send testing email from within the container / the host?

### ISSUE THREAD

**Issue by pkubangbang** [bokysan/docker-postfix#129]
Hi!

I come from this post https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/2630 where there (at the bottom of the page) is a solution using `boky/postfix`. Since I was self-hosting Gitlab (also in a docker container) in a complex network, I found myself inefficient to debug the mail sending process.

The ultimate goal was to achieve mail delivery when a Gitlab user pushed code; this required Gitlab to send email through postfix. Currently the mail sending is not successful, so I would like to first debug the postfix part. **Could you give me some advice on how I can send testing email to the postfix instance?**

Thanks!

Say I have a docker-compose file like this:
```yaml
version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://my-gitlab.com:8000'

        gitlab_rails['smtp_enable'] = true
        # mail-server points to the postfix service, also in this compose file.
        gitlab_rails['smtp_address'] = "mail-server"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_domain'] = "domain-a"

        gitlab_rails['smtp_user_name'] = "user@domain-a"
        gitlab_rails['smtp_password'] = "passwd-xxxxxx"

        gitlab_rails['gitlab_email_from'] = 'robot@domain-a'
        gitlab_rails['gitlab_email_reply_to'] = 'no-reply@my-gitlab.com'
    ports:
      # Note: the internal ports (:8000) should comply with the `external_url`
      #   defined in environment.
      - '8000:8000'
    extra_hosts:
      my-gitlab.com: <the intranet ip addr>
    volumes:
      - './config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    shm_size: '256m'
  # see https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/2630
  mail-server:
    image: boky/postfix
    environment:
      ALLOWED_SENDER_DOMAINS: '??????'
      # Only reachable from intranet
      RELAYHOST: "my-gitlab.com"
    extra_hosts:
      my-gitlab.com: <the intranet ip addr>
volumes:
  gitlab-logs:
  gitlab-data:

```
