### ISSUE TITLE
sasl client authentication not working

### ISSUE THREAD

**Issue by Tipsmark** [bokysan/docker-postfix#131]
I get this error when trying sasl client auth
warning: SASL authentication failure: cannot connect to saslauthd server: No such file or directory"
values set:
        smtpd_sasl_auth_enable: 'yes'
        smtpd_sasl_path: 'smtpd'
        smtp_sasl_password_maps: '/etc/postfix/sasl/smtp_sasl_password_maps'
        cyrus_sasl_config_path: '/etc/postfix/sasl'

any clyes how to properly configure sasl?

**Comment by bokysan** [comment]
Hi,

I would love to help, but this is simply too little to go on. If you can provide me with a repeatable example, I can try reproducing the issue and see what's going on.

**Comment by Tipsmark** [comment]
I found out is has to do with:
saslauthd_path: /var/run/saslauthd in /etc/postfix/sasl/smtpd.conf
however that path gives me permission denied.
So to reproduce, add the above to values and mount a secret containing smtpd.conf and smtp_sasl_password_maps as files into /etc/postfix/sasl dir.

```
secret:
apiVersion: v1
kind: Secret
metadata:
  name: smtp-sasl-password-maps
type: Opaque
stringData:
  smtp_sasl_password_maps: test@lalala test
  smtpd.conf: |
    pwcheck_method: saslauthd
    mech_list: PLAIN LOGIN
    saslauthd_path: /var/run/saslauthd
```

```
  valuesInline:
      postfix:
        smtpd_sasl_auth_enable: 'yes'
        smtpd_sasl_path: 'smtpd'
        smtp_sasl_password_maps: '/etc/postfix/sasl/smtp_sasl_password_maps'
        cyrus_sasl_config_path: '/etc/postfix/sasl'
```

Connecting to mail server.
Connected.
220 smtp.lalala ESMTP Postfix
EHLO COMP123
250-smtp.lalala
250-PIPELINING
250-SIZE
250-VRFY
250-ETRN
250-AUTH PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING
AUTH LOGIN
334 VXNlcm24hbWU6
dGVzdEBiaX2eZGs=
334 UGFzcgevcmQ6
dGVzdsA==
454 4.7.0 Temporary authentication failure: generic failure
Forcing disconnection from SMTP server.
QUIT
221 2.0.0 Bye
Disconnected.
