### ISSUE TITLE
Missing "mail" logs in default container stdout log

### ISSUE THREAD

**Issue by RESP-hub** [bokysan/docker-postfix#134]
Hi Everyone,

Thanks @bokysan and all other supporters for providing this dockerized version of postfix. Really love it's ease of use :-)

Not sure if I configured something wrong or something is up with the stdout logging. I would assume in the default setup (as also found in other issue documentation) that mail logs (FROM:, TO: etc.) would be included in the default logging of the container (pushing it to stdout if no other env. variable is set to log it to file). 

However, I only see these logs pop-up sporadically. When an email is sent, I see DKIM related messages (which I will worry about later), but no mail log messages. When I restart the container or leave it up for a bit longer, I might get an mail log entry 

What am I missing, or is there more going on? The mail delivery etc. work perfectly fine, but I would like to have logging of the emails that are going out.

**My compose file env. variables:** (I did not make any other "direct" changes to main.cf or master.cf config files, the one with the image is used)
<img width="594" alt="Screenshot 2023-08-14 at 15 49 04" src="https://github.com/bokysan/docker-postfix/assets/9774501/18e47758-daac-430a-a26d-d3c14ca377b6">

**Logs that I see most of the time when an email is sent:** (So no mail log, only related to DKIM)
<img width="1061" alt="Screenshot 2023-08-14 at 15 50 47" src="https://github.com/bokysan/docker-postfix/assets/9774501/cdb777f7-1023-4840-82bf-07c5b89a1cbc">

**Logs that I would expect, but are only in the container logs sporadically** (Entry from earlier today):
<img width="640" alt="Screenshot 2023-08-14 at 15 56 48" src="https://github.com/bokysan/docker-postfix/assets/9774501/811ef2d3-9947-464a-8922-dd9b7886e0e3">

Thanks in advance for the assistance!

Kind regards, 
Yoni

**Comment by bokysan** [comment]
Does this happen on the (latest official release)[https://hub.docker.com/layers/boky/postfix/v3.6.1-alpine/images/sha256-105563b432ba2f9828f61bfbd57b85a4b064645f390fbf35bf3ed296b6264e2f?context=explore) as well or only on master?

Master is work-in-progress and can get unstable from time to time.

**Comment by bokysan** [comment]
I've changed the behaviour now and `:latest` should point to the latest release. I cannot reproduce this problem either from `master` or latest release ATM, so I'm closing the issue.

**Comment by RESP-hub** [comment]
@bokysan Sorry for the extremely late reply, I pulled the latest image but still cannot get any mail logs to go to stdout. I tried adding multiple ENV variables to get it to work, but the only option that works is to add POSTFIX_maillog_file: "/var/log/mail.log". This is the only way to inside the container get some sort of email logging to be stored. 

Adding POSTFIX_maillog_file: "/dev/stdout" (as stated by Postfix [here](https://www.postfix.org/MAILLOG_README.html#log-to-stdout)) also did not do the trick. I'm using the image as out of the box as possible, so I am confused as to why the mail log is working directly for you and it is not for me. I am using OpenDKIM though, maybe that in conjunction with Postfix is causing logging issues? As I only see logs from OpenDKIM and not from Postfix.

This is my full compose file used: (I know it is a bit of a mess to link to other custom files on the system, but it works :-))
```
postfix:
    image: boky/postfix:latest
    restart: unless-stopped
    environment:
      TZ: "Europe/Amsterdam"
      ANONYMIZE_EMAILS: "default"
      INBOUND_DEBUGGING: 1
      LOG_FORMAT: "plain"
      POSTFIX_maillog_file: "/dev/stdout"
      POSTFIX_myhostname: "mydomain"
      POSTFIX_myorigin: "mydomain"
      POSTFIX_mydomain: "mydomain"
      POSTFIX_transport_maps: 'texthash:/etc/postfix/CustomTransport'
      ALLOW_EMPTY_SENDER_DOMAINS: "true"
      ALLOWED_SENDING_DOMAINS: ""
      OPENDKIM_Selector: "default"
      OPENDKIM_SigningTable: 'refile:\/etc\/opendkim\/CustomSigningTable'
      OPENDKIM_KeyTable: 'refile:\/etc\/opendkim\/CustomKeyTable'
      OPENDKIM_InternalHosts: 'refile:\/etc\/opendkim\/CustomTrustedHosts'
      OPENDKIM_ExternalIgnoreList: 'refile:\/etc\/opendkim\/CustomTrustedHosts'

    expose:
      - 25
 
    volumes:
    - /var/docker-vol/postfixCONF/dkim-keys:/etc/opendkim/keys
    - /var/docker-vol/postfixCONF/key.table:/etc/opendkim/CustomKeyTable
    - /var/docker-vol/postfixCONF/signing.table:/etc/opendkim/CustomSigningTable
    - /var/docker-vol/postfixCONF/trusted.hosts:/etc/opendkim/CustomTrustedHosts
    - /var/docker-vol/postfixCONF/transport:/etc/postfix/CustomTransport
```

Thanks for the continued assistance!
