### ISSUE TITLE
Connection refused when trying to connect to docker service of boky/postfix from other service

### ISSUE THREAD

**Issue by poulwiel** [bokysan/docker-postfix#156]
I have a host machine on which there is a docker-compose configuration for my services and i would like to use boky/postfix as a e-mail server to send e-mails from my applications (other services). Configuration for boky/postfix in my docker-compose.xml file is as follows:
```
  postfix-email-server:
    image: boky/postfix
    ports:
      - 1587:587
    environment:
      - HOSTNAME=my_real_host_name.com
      - ALLOWED_SENDER_DOMAINS=my_real_host_name.com
      - MYNETWORKS=172.18.0.0/16
```
After starting boky/postfix in a container i see no troubles in logs, it just starts. Then when i try to connect from java-mail implementation from other service inside this docker-compose machine configured to use host: postfix-email-server and port from docker-compose.xml file 1587 i receive: Connection refused exception. But i've also tested it with telnet, trying simply to connect to with this command: #telnet postfix-email-server 1587 this also gives me: telnet: Unable to connect to remote host: Connection refused

I've also tried to use telnet from docker host machine and to my surprise the results are as follow: #telnet postfix-email-server 1587 no such name, which is correct because host machine does not know the service name, but: #telnet 172.18.0.3 1587 gives 'telnet: Unable to connect to remote host: Connection refused' exception and finally: '#telnet localhost 1587' opens connection to postfix. So does this means boky/postfix only accepts connections from localhost? If so, how to send emails from other docker services, localhost is rather special address name and should not be mapped to any other IP than 127.0.0.1

I've also other services (tomcat and mariadb) and they can reach each other just fine.
