### ISSUE TITLE
ServiceMonitor is broken - `selector` is incorrect

### ISSUE THREAD

**Issue by joekrill** [bokysan/docker-postfix#162]
The `ServiceMonitor` specifies this selector in the spec:

```yaml
selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $chart }}
      prometheus: unknown
```

There are 2 problems:

1. `app.kubernetes.io/instance` is always set to match the value "mail" (it seems that `$chart` is always equal to "mail"? I may be reading this helm file wrong though). I think this _should_ be `{{ .Release.Name }}`. Otherwise this won't match if someone names the release anything other than "mail".
2. The `prometheus: unknown` selector will never match anything because it's not applied to any resources, as far as I can tell. So I'm not entirely sure the purpose of it. I think this should just be removed entirely.

I can throw up a PR to address this tomorrow, but let me know if I'm missing something here.
