### ISSUE TITLE
Ingress support

### ISSUE THREAD

**Issue by mpetuska** [bokysan/docker-postfix#166]
Hi, I'm trying to deploy this via helm and while everything does boot up fine inside the cluster, for whatever reason I cannot get my custom ingress with traefic controller to find an endpoint of the deployed service. It would be great if the chart itself would come with ingress configuration options or at least some sample setups how to properly achieve this. 

Here's my ingress definition in case you need it for debugging:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smtp
  namespace: smtp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - my.custom.domain
      secretName: smtp-tls
  rules:
    - host: my.custom.domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mail
                port:
                  name: smtp

```

With that traefic keeps complaining with these
```
level=error msg="Skipping service: no endpoints found" serviceName=mail providerName=kubernetes servicePort="&ServiceBackendPort{Name:smtp,Number:0,}" ingress=smtp namespace=smtp
```
