### ISSUE TITLE
Settings not applied consistently

### ISSUE THREAD

**Issue by MrEbbinghaus** [bokysan/docker-postfix#168]
The default `mynetwork` setting isn't applied consistently. 

Problem is, I can't reliably reproduce it. Sometimes when I run `docker compose up` it just doesn't get set, most of the time it does. I haven't changed any settings between restarts..

----

I don't have `POSTFIX_mynetwork` set and I don't have any config in files, only docker labels.

On startup the logs show the right networks:
```
INFO  Applying custom postfix setting: mynetworks=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
```

But postconf gives me:
```
postconf | grep "mynetworks ="
mynetworks = 127.0.0.1/32 172.23.0.5/32
```

There is no setting set in `main.cf`

```
# Alternatively, you can specify the mynetworks list by hand, in
# which case Postfix ignores the mynetworks_style setting.
#
# Specify an explicit list of network/netmask patterns, where the
# mask specifies the number of bits in the network part of a host
# address.
#
# You can also specify the absolute pathname of a pattern file instead
# of listing the patterns here. Specify type:table for table-based lookups
# (the value on the table right-hand side is not used).
#
#mynetworks = 168.100.3.0/28, 127.0.0.0/8
#mynetworks = $config_directory/mynetworks
#mynetworks = hash:/etc/postfix/network_table

# ...
myhostname = <redacted>
# mynetworks is missing here. Most of the time it's: mynetworks = 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
myorigin = <redacted>
```
(And nothing at the end of the file as well.)

**Comment by bokysan** [comment]
Well, this is a first one.

Unfortunately, you have not given me a lot to go on:
- which version of the image are you using
- which variant (Debian, Alpine...)
- what's your startup procedure / configuration settings for running the image
- does this happen with `mynetworks` only, or are the other settings affected as well
- do you have any volumes bound
- ...

So, until I'm able to reproduce the issue, unfortunately, I don't think I can help.

**Comment by MrEbbinghaus** [comment]
It's pretty weird and I'm pretty confused about what could cause that behavior. I've looked at the startup scripts in this repo and found nothing on first glance. 

But you are right, I could at least have provided more details:

For now I have only seen `mynetworks` missing. Which I noticed, because Postfix started to reject mail from the local Mailman.

I'm using `boky/postfix:latest-alpine` (at the time of writing that's `c2b9a8a68d73`)
I use it as a docker compose service with `restart: unless-stopped`. 
Port 25 is exposed to the host and the container is part a bridge network for mailman to be able to talk via LMTP. 

## Config
(Everything configured via the `POSTFIX_` environment variables.)

I have two binds:
```yaml
volumes:
      - ./volumes/mailman-core:/opt/mailman/core:ro
      - /host/keys:/etc/opendkim/keys
```
`/opt/mailman/core` contains `transport_maps`, `local_recipient_maps` and `relay_domains` that are auto-generated by Mailman. 

Additionally I have set `mydomain` and `myorigin`. 

```yaml
DKIM_AUTOGENERATE: "true"
DKIM_SELECTOR: 10-2023

POSTFIX_mydomain: <redacted>
POSTFIX_myorigin: <redacted> # Default: $myhostname localhost.$mydomain localhost

POSTFIX_recipient_delimiter: +
POSTFIX_unknown_local_recipient_reject_code: 550
POSTFIX_owner_request_special: "no"
POSTFIX_transport_maps: regexp:/opt/mailman/core/var/data/postfix_lmtp
POSTFIX_local_recipient_maps: regexp:/opt/mailman/core/var/data/postfix_lmtp
POSTFIX_relay_domains: regexp:/opt/mailman/core/var/data/postfix_domains
# And a bunch of restrictions. (client, helo, sender, recipient)
# They use `permit_mynetworks` which of course fails if mynetworks isn't set.
```
