### ISSUE TITLE
530 when relaying through AWS SES

### ISSUE THREAD

**Issue by 12nick12** [bokysan/docker-postfix#178]
Hi, I've verified the RELAYHOST, RELAYHOST_USERNAME, and RELYHOST_PASSWORD are set correctly, but am still receiving this error.

**Comment by 12nick12** [comment]
This is my docker-compose.yml

```
name: postfix-docker
services:
  postfix:
    container_name: postfix
    environment:
      - ALLOWED_SENDER_DOMAINS=DOMAIN1.com DOMAIN2.com
      - RELAYHOST=email-smtp.us-east-1.amazonaws.com:2587
      - RELAYHOST_USERNAME=$USER
      - RELYHOST_PASSWORD=$PASS
      - POSTFIX_smtp_tls_security_level=secure
    ports:
      - 1587:587
    image: boky/postfix
```
