### ISSUE TITLE
A restrictive security context causes Read-only file system error

### ISSUE THREAD

**Issue by giorgionanfa** [bokysan/docker-postfix#199]
Hi, I am using the mail chart and trying to set this **security context** (necessary for project policies):
```yaml
pod:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
container:
  postfix:
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      readOnlyRootFilesystem: true
```

After the chart is installed, the pod continuously restarts with the following logs:

> chmod: changing permissions of '/scripts/common-run.sh': Read-only file system
> chmod: changing permissions of '/scripts/common.sh': Read-only file system
> chmod: changing permissions of '/scripts/cron.sh': Read-only file system
> chmod: changing permissions of '/scripts/email-anonymizer.sh': Read-only file system
> chmod: changing permissions of '/scripts/healthcheck.sh': Read-only file system
> chmod: changing permissions of '/scripts/opendkim.sh': Read-only file system
> chmod: changing permissions of '/scripts/postfix.sh': Read-only file system
> chmod: changing permissions of '/scripts/run.sh': Read-only file system

Do you have any ideas on how I can solve this problem or if it's possible? Thanks a lot!
