### ISSUE TITLE
Issues with smtpd_tls_security_level "may" setting

### ISSUE THREAD

**Issue by QustodioPablo** [bokysan/docker-postfix#206]
I installed this chart in our cluster, and after testing it usint telnet, I verified I was able to send emails.
When trying to use the service through another application, I noticed the service was failing to send emails: Turns out the initial testing I did, I was using the container's port 25, but the chart makes use only of port 587.

Using port 587, I get an SSL error, since we don't have SSL setup in the smtp server. And setting `smtpd_tls_security_level` to `none` makes the call to our relay (AWS' SES) to fail with `530 Must issue a STARTTLS command first`

After inspecting the chart, I see the ports used in the pod are not parameterized. Could this be implemented?

**Comment by bokysan** [comment]
I'm sorry, but I really cannot make heads and tails out of your question:
- you're saying you did tests on container's port 25, but by default this image exposes only 587
- you're talking about submitting mail to the container, but in the same sentence you talk about SES -- so forwarding emails _from_ the container onwards.

So, to be able to even help you debug:
- which version of the image are you using
- which variant (ubuntu, alpine...)
- were are you deploying (helm, docker)
- how are you deploying (your `values.yaml` or `docker-compose.yaml` or something similar)
- what are you trying to achieve
- how you are doing it

And before that, just checking -- have you checked Postfix's documentation on [`smtpd_tls_security_level`](https://www.postfix.org/postconf.5.html#smtpd_tls_security_level), [this image's documentation](https://github.com/bokysan/docker-postfix?tab=readme-ov-file#postfix_smtp_tls_security_level) and [Postfix TLS documentation](https://www.postfix.org/TLS_README.html)?

**Comment by QustodioPablo** [comment]
Ah, sorry for not giving more context!

I used helm chart version 4.0.2 to deploy the service in our cluster, using the default docker image set in the helm chart (version 4.0.2-debian, amd64 platform)
The values file is this one (minus redacted info):
```
config:
  general:
    ALLOWED_SENDER_DOMAINS: xxxxxxxxx.com
    RELAYHOST: '[email-smtp.us-east-1.amazonaws.com]:587'
    RELAYHOST_PASSWORD_FILE: /var/lib/secret/key_secret
    RELAYHOST_USERNAME: XXXXXXXXXXX # AWS access_key_id
  postfix:
    smtpd_tls_security_level: may
extraVolumeMounts:
  - mountPath: /var/lib/secret
    name: ses-secret
    readOnly: true
extraVolumes:
  - name: ses-secret
    secret:
      secretName: ses-secret # Kubernetes secret with the AWS access_secret 
```

After the installation, I made a port-forward for port 25 in the container to my local machine, and then connected through telnet.
With telnet I was able to send an email, verifying AWS' relay was correctly configured.

If I set `smtpd_tls_security_level` to may, when another service calls postfix, I get a certificate error when establishing the connection between the other service and postfix.
If I set `smtpd_tls_security_level` to none, the connection between the other service and postfix is successful, but the connection against AWS fails. This behavior is expected as SES requires STARTTLS

From what I gather from the documentation, the `smtpd_tls_security_level` set to `may` should be what I am looking for, since it uses STARTTLS against remote SMTP servers, but doesn't use TLS against clients, which is exactly what I'm trying to do. But it seems it is still trying to use TLS.
