### ISSUE TITLE
Can't send mail - all recipients were rejected

### ISSUE THREAD

**Issue by AlissonRS** [bokysan/docker-postfix#209]
I have a working setup using Google Workspace SMTP Relay, I'm testing locally and added my own IP address into Google Console, I managed to send emails just fine with my primary email address.

I added a secondary domain to my Google Workspace, and added an alternate email address to my user, so now I have:

- me@myprimarydomain.com (this is working fine)
- me@mysecondarydomain.com (this is not)

My docker-compose looks like this:
```
  postfix:
    image: boky/postfix:latest
    container_name: postfix
    restart: always
    environment:
      - RELAYHOST=smtp-relay.gmail.com:587
      - ALLOWED_SENDER_DOMAINS=mysecondarydomain.com myprimarydomain.com
    ports:
      - "1587:587"
      - "25:25"
```

When I try sending email from my secondary email address, I get this error:

> Error: Can't send mail - all recipients were rejected: 554 5.7.1 <my-test-recipient@gmail.com>: Recipient address rejected: Access denied

_(my-test-recipient is a valid test email I own, and I have successfully received emails using my primary email for sending)_

I also tried changing "Allowed Senders" to "Only addresses in my domain" in the SMTP Relay settings in Workspace, just in case.

![image](https://github.com/user-attachments/assets/884ec244-bf0f-4d80-824c-882ff22f5153)

Both my domains (primary and secondary) have DKIM, DMARC and SPF enabled, though that should be handled by Google.

I can send emails from Gmail manually just fine.

Do I need any extra setup to support an alternate domain? Or perhaps Google itself doesn't support using alternate domains with SMTP Relay (though it works fine from Gmail, from there I can use my alternate domain as a sender).
