### ISSUE TITLE
logrotate cron failing

### ISSUE THREAD

**Issue by sushain97** [bokysan/docker-postfix#212]
The out-of-the-box Helm setup with metrics seems to enable `logrotate` with a dedicated config for `/var/log/mail.log`. Unfortunately, `logrotate` seems to fail every day as a result and generate an email to `root`:

```
root@postfix-mail-0:/tmp# /etc/cron.daily/logrotate
error: rsyslog:1 duplicate log entry for /var/log/mail.log
error: found error in file rsyslog, skipping
root@postfix-mail-0:/tmp# echo $?
1

root@postfix-mail-0:/tmp# grep -R mail /etc/logrotate*
/etc/logrotate.d/logrotate.conf:/var/log/mail.log {
/etc/logrotate.d/rsyslog:/var/log/mail.log

root@postfix-mail-0:/tmp# cat /etc/logrotate.d/rsyslog
/var/log/syslog
/var/log/mail.log
/var/log/kern.log
/var/log/auth.log
/var/log/user.log
/var/log/cron.log
{
        rotate 4
        weekly
        missingok
        notifempty
        compress
        delaycompress
        sharedscripts
        postrotate
                /usr/lib/rsyslog/rsyslog-rotate
        endscript
}

root@postfix-mail-0:/tmp# cat /etc/logrotate.d/logrotate.conf
/var/log/mail.log {
    copytruncate
    rotate 1
    monthly
    minsize 1M
    compress
    missingok
    notifempty
    dateext
    olddir /var/log/
    maxage 90
}
```

My Helm values:
```yaml
serviceAccount:
  create: false
nodeSelector:
  kubernetes.io/hostname: XXX
resources:
  requests:
    memory: 128Mi
    cpu: 500m
  limits:
    memory: 256Mi
    cpu: 1000m
config:
  general:
    TZ: America/Los_Angeles
    ALLOWED_SENDER_DOMAINS: XXX
    RELAYHOST: smtp.gmail.com:587
    RELAYHOST_USERNAME: XXX
    XOAUTH2_CLIENT_ID: XXX
  postfix:
    smtp_tls_security_level: encrypt
    smtpd_tls_security_level: none
existingSecret: xoath2
pod:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
container:
  postfix:
    securityContext:
      allowPrivilegeEscalation: false
persistence:
  storageClass: local-path
  size: 100Mi
extraEnv:
  - name: POSTFIX_myhostname
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
metrics:
  enabled: true
  serviceMonitor:
    enabled: false
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9154"
```
