### ISSUE TITLE
Healthcheck does not work when smtpd_upstream_proxy_protocol is enabled

### ISSUE THREAD

**Issue by imro2** [bokysan/docker-postfix#226]
Could not get the health-check to work properly after I enabled proxy protocol. Had to copy the healthcheck.sh locally, and modify the postifix check to read like this:

```
check_postfix() {
    printf "PROXY TCP4 192.168.2.1 1.2.3.4 12345 54321\nEHLO healthcheck\nquit\n" | \
    { while read l ; do sleep 1; echo $l; done } | \
    nc -w 2 127.0.0.1 587 | \
    grep -qE "^220.*ESMTP Postfix"
}
```

And add this to my compose

````
    volumes:
      - ./healthcheck.sh:/healthcheck.sh
    healthcheck:
      test:
        - CMD-SHELL
        - /healthcheck.sh
````
