### ISSUE TITLE
DKIM files (KeyTable, SigningTable, TrustedHosts) keep being overridden?

### ISSUE THREAD

**Issue by conficient** [bokysan/docker-postfix#234]
Trying to get postfix working with _DKIM_ for multiple domains. I only need to send out emails, so no inbound requirements.

When I run the container, it seems the `KeyTable`, `SigningTable` and `TrustedHosts` files are being overwritten?

I've set up `/opt/postfix/dkim/` with completed versions of these files for the domains I need to handle, and created the keys in `/opt/postfix/dkim/keys/` with a folder for each domain; e.g. `/opt/postfix/dkim/keys/example.com/default.private`

The `docker-compose.yml` is as follows:
```yml
version: '3'

services:
  postfix:
    image: boky/postfix
    restart: unless-stopped
    container_name: postfix
    ports:
      - "587:587"
    environment:
      - ALLOW_EMPTY_SENDER_DOMAINS=true
      - DKIM_ENABLE=true
      - POSTMASTER_ADDRESS=admin@example.com
    volumes:
      - /opt/postfix/dkim/keys:/etc/opendkim/keys
      - /opt/postfix/dkim/KeyTable:/etc/opendkim/KeyTable
      - /opt/postfix/dkim/SigningTable:/etc/opendkim/SigningTable
      - /opt/postfix/dkim/TrustedHosts:/etc/opendkim/TrustedHosts
```
If I append `:ro` to the volumes to stop it overwriting, I get an error

Suggestions welcomed!
