### ISSUE TITLE
🙏 Can't send emails: "Recipient address rejected: Domain not found"

### ISSUE THREAD

**Issue by simovicaleksa** [bokysan/docker-postfix#237]
Hi guys,

I have been working on creating a self-hosted send-only mail server for handling my authentication notifications (verify email, reset password, etc.).

## Problem

Whenever I try to send email from my **backend** I get the following error in the postfix logs: 

```sh
postfix/smtpd[2063]: NOQUEUE: reject: RCPT from app1 <user@gmail.com>: Recipient address rejected: Domain not found; from=<noreply@mydomain.com> to=<user@gmail.com> proto=ESMTP helo=<[127.0.0.1]>
# Simplified error: Recipient address rejected: Domain not found;
```

I don't understand where my implementation failing. Is postfix struggling to resolve gmail.com?

## Docker, DNS & Backend Setup

```yml
services:
  postfix:
    image: boky/postfix:v4.4.0
    environment:
      ALLOWED_SENDER_DOMAINS: ${NEXT_PUBLIC_DOMAIN} # mydomain.com
      DKIM_DOMAINS: ${NEXT_PUBLIC_DOMAIN} # mydomain.com
      DKIM_AUTOGENERATE: 1
    volumes:
      - postfix_data:/var/spool/postfix
      - postfix_dkim:/etc/opendkim/keys
    networks:
      - internal

volumes:
  postfix_data:
  postfix_dkim:

networks:
  internal:
    internal: true
```

DNS setup for "mydomain.com":

| **Host**                        | **TTL** | **Class** | **Type** | **Value**                                  |
| ------------------------------- | ------- | --------- | -------- | ------------------------------------------ |
| `mail.mydomain.com.`            | 1       | IN        | A        | 1.2.3.4                                    |
| `mydomain.com.`                 | 1       | IN        | MX       | 10 mail.mydomain.com.                      |
| `_dmarc.mydomain.com.`          | 1       | IN        | TXT      | "v=DMARC1; p=reject; fo=1; pct=100"        |
| `mydomain.com.`                 | 1       | IN        | TXT      | "v=spf1 a mx ip4:1.2.3.4 -all"             |
| `mail._domainkey.mydomain.com.` | 1       | IN        | TXT      | "v=DKIM1; h=sha256; k=rsa; s=email; p=..." |

I have also done the following:

- [x] Reverse DNS record pointing `1.2.3.4` -> `mydomain.com`.
- [x] Unblocked mail ports (25, 465) for outbound traffic on my VPS provider (Hetzner)
- [ ] Port 587 should be unblocked by default

My backend implementation:

```ts
import nodemailer from "nodemailer";

const emailClient = nodemailer.createTransport({
  host: "postfix",
  port: 587,
  secure: false,
  tls: {
    rejectUnauthorized: false,
  },
});

await emailClient.sendMail({
  from: `Contact Form <noreply@mydomain.com>`,
  to: `user@gmail.com`,
  subject: `Email Subject`,
  text: `<email content text>`,
});
```

## Final Words

If you have any ideas or tips that might steer me in the right direction they would be highly appreciated. Thank you.

**Comment by simovicaleksa** [comment]
@bokysan Thank you very much for not closing the issue right away. Your intuition was right that DNS was the problem. In my `compose.yml` I added Postfix service to the `internal` network group, thus closing it's access to the internet. Adding it to a bridge network group as well fixed my issue and my mailserver is now working perfectly.

```yml
services:
  postfix:
    image: boky/postfix:v4.4.0
    environment:
      ALLOWED_SENDER_DOMAINS: ${NEXT_PUBLIC_DOMAIN} # mydomain.com
      DKIM_DOMAINS: ${NEXT_PUBLIC_DOMAIN} # mydomain.com
      DKIM_AUTOGENERATE: 1
    volumes:
      - postfix_data:/var/spool/postfix
      - postfix_dkim:/etc/opendkim/keys
    networks:
      - internal
      - bridge # 2. add postfix service to the bridge network group

volumes:
  postfix_data:
  postfix_dkim:

networks:
  internal:
    internal: true
  # 1. add a network with drive bridge
   bridge:
    driver: bridge
```

Thank you for the awesome image and debug suggestion, I cannot express how much it has helped me ❤️
