### ISSUE TITLE
Connection via localhost refused

### ISSUE THREAD

**Issue by waynehaffenden** [bokysan/docker-postfix#26]
I have your docker image running on my swarm setup with the following config:

```
version: "3.8"

services:
  smtp:
    image: boky/postfix
    ports:
      - 587:587
    networks:
      - relay
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - HOSTNAME=myhostname
      - RELAYHOST=myrelay
      - ALLOWED_SENDER_DOMAINS=mydomain

networks:
  relay:
    external: true
```

When I try sending a test email from it using s-nail on Debian 10 it fails with this error message:

s-nail: SMTP: Resource temporarily unavailable
s-nail: Unexpected EOF on SMTP connection

When using s-nail to send directly to my SMTP host it works as expected, it appears it's receiving an unexpected output from the docker SMTP server, any ideas?

Thank you
