### ISSUE TITLE
myhostname is added after each restart

### ISSUE THREAD

**Issue by denis-antonik** [bokysan/docker-postfix#37]
After each restart of dockers in main.cf file (on volume) added new string with myhostname, old string with this param are commented.

> #myhostname = 214c7f4ad504
> mynetworks = 127.0.0.0/8,172.20.0.0/16
> #myhostname = 73c3c5480272
> #myhostname = postfix-smtp-relay
> #myhostname = postfix-smtp-relay
> myhostname = postfix-smtp-relay

Part of my docker-compose
```
  postfix-smtp-relay:
    image: boky/postfix
    container_name: postfix-smtp-relay
    hostname: postfix-smtp-relay
    environment:
      POSTFIX_myhostname: postfix-smtp-relay
      POSTFIX_maillog_file: "/var/log/mail.log"
      LOG_FORMAT: plain
      MYNETWORKS: "127.0.0.0/8,172.20.0.0/16"
```
Only this parameter is repeated, is this expected behavior or a bug?
