### ISSUE TITLE
Usage in docker-compose

### ISSUE THREAD

**Issue by slhck** [bokysan/docker-postfix#4]
I want to use this in a docker-compose project (Mattermost, actually), which uses [the following `docker-compose.yml` file](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml).

How would I go about adding this image so that the web container can send email using it?

I've tried adding:

```
  mail:
    image: boky/postfix
    environment:
      - HOSTNAME=mail
```

And then specifying `mail` as the outgoing SMTP server with port 587 in Mattermost, but it says:

> Connection unsuccessful: SendMail: Failed to open connection, dial tcp 172.19.0.5:587: connect: connection refused

I've also tried adding `expose: [587]`, but I got the same error.

Do I need to explicitly map some ports, or do it through the Docker host instead?

**Comment by bokysan** [comment]
This question unfortunately has nothing to do with this image.

But to help you out: You need to link the container to be able to see it from other containers.

You'd need something like this:
```
  mail:
    image: boky/postfix
    ...
  web:
    links:
    - mail:mail
```

See https://docs.docker.com/compose/networking/
