### ISSUE TITLE
health check

### ISSUE THREAD

**Issue by bryan-gilbert** [bokysan/docker-postfix#40]
I'm seeking a health check to verify if postfix is running.  The following is something I developed that seems to work.

Might you consider  adding the following to your project's sample docker compose file or to your documentation?

d-c.yml
```
version: '3'
services:
  postfix:
    image: boky/postfix
    expose:
      - "587"
    environment:
      - DKIM_AUTOGENERATE=1
      - ALLOWED_SENDER_DOMAINS
    restart: always
    volumes:
      - "./dkimkeys:/etc/opendkim/keys"
    healthcheck:
      test: netstat -l | grep smtp
      interval: 1m
      timeout: 10s
      retries: 3
```

The healthcheck uses netstat, which is installed in the linux image used by this project.  Ask netstat to list all listening ports. Use grep to see if something (e.g. postfix) is listening on the smtp port.  Grep returns 0 exit code if it finds a match and 1 when there is no match.
