### ISSUE TITLE
Untrusted TLS connection established

### ISSUE THREAD

**Issue by tinuva** [bokysan/docker-postfix#51]
When trying to send a test email to gmail, I see the following logs:

```
postfix         | 2021-01-24T14:43:33.171226+00:00 INFO    postfix/smtp[138]: certificate verification failed for gmail-smtp-in.l.google.com[108.177.126.26]:25: untrusted issuer /OU=GlobalSign Root CA - R2/O=GlobalSign/CN=GlobalSign
postfix         | 2021-01-24T14:43:33.171270+00:00 INFO    postfix/smtp[138]: Untrusted TLS connection established to gmail-smtp-in.l.google.com[108.177.126.26]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256
postfix         | 2021-01-24T14:43:33.171302+00:00 INFO    postfix/smtp[138]: 3C1D8C1D28: Server certificate not trusted
postfix         | 2021-01-24T14:43:35.880273+00:00 INFO    postfix/smtp[138]: certificate verification failed for alt1.gmail-smtp-in.l.google.com[142.250.4.27]:25: untrusted issuer /OU=GlobalSign Root CA - R2/O=GlobalSign/CN=GlobalSign
postfix         | 2021-01-24T14:43:35.880327+00:00 INFO    postfix/smtp[138]: Untrusted TLS connection established to alt1.gmail-smtp-in.l.google.com[142.250.4.27]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256
postfix         | 2021-01-24T14:43:35.880358+00:00 INFO    postfix/smtp[138]: 3C1D8C1D28: Server certificate not trusted
postfix         | 2021-01-24T14:43:38.262954+00:00 INFO    postfix/smtp[138]: certificate verification failed for alt2.gmail-smtp-in.l.google.com[108.177.97.26]:25: untrusted issuer /OU=GlobalSign Root CA - R2/O=GlobalSign/CN=GlobalSign
postfix         | 2021-01-24T14:43:38.262999+00:00 INFO    postfix/smtp[138]: Untrusted TLS connection established to alt2.gmail-smtp-in.l.google.com[108.177.97.26]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256
postfix         | 2021-01-24T14:43:38.263040+00:00 INFO    postfix/smtp[138]: 3C1D8C1D28: Server certificate not trusted
postfix         | 2021-01-24T14:43:39.720356+00:00 INFO    postfix/smtp[138]: certificate verification failed for alt3.gmail-smtp-in.l.google.com[74.125.28.26]:25: untrusted issuer /OU=GlobalSign Root CA - R2/O=GlobalSign/CN=GlobalSign
postfix         | 2021-01-24T14:43:39.720399+00:00 INFO    postfix/smtp[138]: Untrusted TLS connection established to alt3.gmail-smtp-in.l.google.com[74.125.28.26]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256
postfix         | 2021-01-24T14:43:39.720437+00:00 INFO    postfix/smtp[138]: 3C1D8C1D28: Server certificate not trusted
postfix         | 2021-01-24T14:43:41.269754+00:00 INFO    postfix/smtp[138]: certificate verification failed for alt4.gmail-smtp-in.l.google.com[74.125.137.26]:25: untrusted issuer /OU=GlobalSign Root CA - R2/O=GlobalSign/CN=GlobalSign
postfix         | 2021-01-24T14:43:41.269820+00:00 INFO    postfix/smtp[138]: Untrusted TLS connection established to alt4.gmail-smtp-in.l.google.com[74.125.137.26]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256
```

I can see you do have ca-certificates package from alpine in the docker image, I am just not sure why I get the above message.

**Comment by bokysan** [comment]
I'll need more context, could you share your container configuration (environment variables) and how exactly you tried to send the mail, omitting any personal information and passwords.

Thank you.

**Comment by tinuva** [comment]
I think it is fixed now.

Original config with the issue:
```
  postfix:
    container_name: postfix
    image: boky/postfix
    restart: always
    environment:
      - ALLOW_EMPTY_SENDER_DOMAINS=true
      - POSTFIX_mynetworks=127.0.0.0/8 10.0.0.0/8 172.0.0.0/8 192.168.0.0/16 
      - POSTFIX_smtpd_client_restrictions=permit_mynetworks
      - POSTFIX_smtp_use_tls=yes
      - POSTFIX_smtp_sasl_security_options=noanonymous
      - POSTFIX_smtp_tls_security_level=encrypt
      - POSTFIX_smtp_tls_security_level=verify
      - POSTFIX_smtp_tls_loglevel=1
    labels:
      - com.centurylinklabs.watchtower.enable=true
```

Working config now:
```
  postfix:
    container_name: postfix
    image: boky/postfix
    restart: always
    environment:
      - ALLOW_EMPTY_SENDER_DOMAINS=true
      - POSTFIX_mynetworks=127.0.0.0/8 10.0.0.0/8 172.0.0.0/8 192.168.0.0/16 
      - POSTFIX_smtpd_client_restrictions=permit_mynetworks
      - POSTFIX_smtp_sasl_security_options=noanonymous
      - POSTFIX_smtp_tls_loglevel=1
    labels:
      - com.centurylinklabs.watchtower.enable=true
```
