### ISSUE TITLE
Sockets in a persistent volume

### ISSUE THREAD

**Issue by bcroq** [bokysan/docker-postfix#66]
We get errors when backuping the persistent volume used for `/var/spool/mail` because it contains a lot of sockets.

Is it a good idea to put these sockets in a persistent volume?

**Comment by bokysan** [comment]
> because it contains a lot of sockets

Can you provide a bit more info? Postfix is directed to use `/var/spool/mail` as the `mail_spool_directory`.

I am not familiar with any configuration which would direct postfix to put the socket connections elsewhere.

**Comment by bcroq** [comment]
I use the 3.0.0 chart with persistence enabled.

Here is the configuration:
```yaml
mail:
  fullnameOverride: mail
  config:
    general:
      ALLOWED_SENDER_DOMAINS: example.com
      RELAYHOST: "[mailhog.ns.svc.cluster.local]:1025"
      TZ: Europe/Paris
  persistence:
    enabled: true
    size: 100Mi
    existingClaim: my-claim

```

Here is the list of the sockets found in the volume:
```console
$ kubectl -n ns exec -it mail-0 -- /bin/bash
bash-5.1# find /var/spool/postfix/ -type s
/var/spool/postfix/private/scache
/var/spool/postfix/private/error
/var/spool/postfix/private/tlsmgr
/var/spool/postfix/private/retry
/var/spool/postfix/private/virtual
/var/spool/postfix/private/proxymap
/var/spool/postfix/private/local
/var/spool/postfix/private/relay
/var/spool/postfix/private/smtp
/var/spool/postfix/private/lmtp
/var/spool/postfix/private/discard
/var/spool/postfix/private/proxywrite
/var/spool/postfix/private/anvil
/var/spool/postfix/private/defer
/var/spool/postfix/private/rewrite
/var/spool/postfix/private/verify
/var/spool/postfix/private/trace
/var/spool/postfix/private/bounce
/var/spool/postfix/public/pickup
/var/spool/postfix/public/qmgr
/var/spool/postfix/public/showq
/var/spool/postfix/public/cleanup
/var/spool/postfix/public/flush
/var/spool/postfix/public/postlog
```
