### ISSUE TITLE
helm chart: DKIM

### ISSUE THREAD

**Issue by zerthimon** [bokysan/docker-postfix#83]
Is it possible to install the chart with pre-generated DKIM keys ?
Has anyone done that and can share their values.yaml file ?

**Comment by zerthimon** [comment]
I figured out how to add DKIM without changing the helm chart:
Here are my values
```
config:
  general:
    ALLOWED_SENDER_DOMAINS: foo.bar

secret:
  dkim-private: |
    -----BEGIN RSA PRIVATE KEY-----
    < redacted >
    -----END RSA PRIVATE KEY-----

persistence:
  enabled: false

extraVolumes:
  - name: dkim-private
    secret:
      secretName: mail
      items:
        - key: dkim-private
          path: foo.bar.private

extraVolumeMounts:
  - name: dkim-private
    mountPath: /etc/opendkim/keys
    readOnly: true
```
It works, but there are two minor issues:
1. The private keys ends up in the container env (since the `envFrom:secretRef`)
2. `secretName` in `extraVolumes` needs to be set to the release name.
