### ISSUE TITLE
helm chart: persistence, allow kubernetes default storageClassName

### ISSUE THREAD

**Issue by zerthimon** [bokysan/docker-postfix#84]
Currently there is no way to use kubernetes default SC due to:
```
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
```
To use default SC, the `storageClassName` should not be specified at all in the `volumeClaimTemplate`: like this:
```
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.worker.volume.size }}
```
