### ISSUE TITLE
Can't sent email - loops back to myself

### ISSUE THREAD

**Issue by AntoineDavidSupersoniks** [bokysan/docker-postfix#88]
Hello,

I can't send a mail to a recipient, if the domain of the mail is the mail defined in hostname.

conf YAML :

```yaml
services:
  postfix:
    hostname: domain.com
    build:
      context: Postfix
      dockerfile: Dockerfile
    container_name: postfix
    environment:
      - TZ="Europe/Paris"
      - FORCE_COLOR=1
      - INBOUND_DEBUGGING=1
      - ALLOWED_SENDER_DOMAINS=domain.com
      - ALLOW_EMPTY_SENDER_DOMAINS=0
      - LOG_FORMAT=plain
      - POSTFIX_maillog_file=/var/log/postfix.log
      - POSTFIX_myhostname=${POSTFIX_HOSTNAME}
    volumes:
      - postfix_vol:/var/log
      - dkimkey_vol:/etc/opendkim/keys
    restart: always
    ports:
      - "1587:587"
```
With this configuration I can send mails to anyone except to a mail in `@domain.com`

The error :

```bash
Oct 07 13:04:23 supersoniks postfix/smtp[229]: 8A7D11657: to=<contact@domain.com>, relay=none, delay=0.01, delays=0/0/0/0, dsn=5.4.6, status=bounced (mail for domain.com loops back to myself)
```

I think postfix is trying to deliver the mail locally, but myDestination is not specified

Is this a bug or does someone have an idea to solve this problem?

Thanks
