### ISSUE TITLE
chown: /var/spool/postfix/: Operation not permitted when using persistent volume claims

### ISSUE THREAD

**Issue by erc7** [bokysan/docker-postfix#97]
Deploying via helm.

Config:
```
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 128Mi
  storageClass: efs-sc
```

Storageclass:
```
Name:                  efs-sc
IsDefaultClass:        Yes
Annotations:           meta.helm.sh/release-name=aws-efs-csi-driver,meta.helm.sh/release-namespace=kube-system,storageclass.kubernetes.io/is-default-class=true
Provisioner:           efs.csi.aws.com
Parameters:            basePath=/dynamic_provisioning,directoryPerms=700,fileSystemId=*******,gidRangeEnd=2000,gidRangeStart=1000,provisioningMode=efs-ap
AllowVolumeExpansion:  <unset>
MountOptions:
  tls
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate
Events:             <none>
```

Log:
```
★★★★★ POSTFIX STARTING UP ★★★★★                    
‣ INFO  Not setting any timezone for the container 
‣ INFO  Using plain log format for rsyslog.        
‣ NOTE  Using smart filter for email anonymization.
chown: /var/spool/postfix/: Operation not permitted
```

The persistent volume claim seems to be bound properly when creating the deployment. Am I missing something?

**Comment by erc7** [comment]
related: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/300

is it possible to have a toggle similar to the one stated in above:
```
initChownData:
  enabled: false
```

**Comment by bokysan** [comment]
Yes, of course. I can start working on next month. 


Pull requests are welcome, though.

**Comment by dominik-bln** [comment]
FYI, this can be fixed via the existing `extraInitContainers` field currently:

```yaml
extraInitContainers: |
    - name: volume-mount-hack
      image: busybox:1.35.0-glibc
      command: ["sh", "-c", "chown -R 100:102 /var/spool/postfix/private && chown -R 100:102 /var/spool/postfix/public "]
      volumeMounts:
      - mountPath: /var/spool/postfix/private
        name: private
      - mountPath: /var/spool/postfix/public
        name: public
```
