### ISSUE TITLE
Receiving emails in local mailbox with a catch-all account

### ISSUE THREAD

**Issue by paulo-graca** [bokysan/docker-postfix#99]
This is more like a documentation request than an issue. I'm doing some tests with a Wordpress instance using docker and for sending emails I'm testing this image. It works as expected, mostly out-of-the-box (without changes). But, without having to do configurations on Wordpress itself. I needed to have a local catch-all account for receiving all Wordpress sent emails.

Without the use of containers I configured a virtual map with a regular expression like:
```
/.+@.+/ root@localhost
```
this will redirect all emails to a root account (kind of a catch-all account) at localhost.

I start experimenting with your image and I will share the configurations I'm kind of using in my `docker-compose.yml` in order do have a catch-all account that stores all sent email in a local mailbox:

```
  postfix:
    # https://github.com/bokysan/docker-postfix
    image: boky/postfix
    environment:
      ALLOW_EMPTY_SENDER_DOMAINS: "true"
      POSTFIX_mydestination: "$$myhostname, localhost.$$mydomain, localhost.localdomain, localhost"
      POSTFIX_home_mailbox: "mail/"
    volumes:
      - /var/spool/example.com/postfix:/var/spool/postfix
      - /root/mail/example.com:/root/mail/
      - /etc/postfix/virtual:/etc/postfix/virtual:ro
      - /etc/postfix/virtual-regexp:/etc/postfix/virtual-regexp:ro
      - ./postfix-config:/docker-init.db
    restart: always
```

all sent emails will be written to `/root/mail/example.com` folder in my host server. I'm mounting this folder in order to check the emails.
This is the required configuration to have emails stored in a local mailbox. Without it, the container will not know what is `localhost`.
```
POSTFIX_mydestination: "$$myhostname, localhost.$$mydomain, localhost.localdomain, localhost"
```

Then my `/etc/postfix/virtual-regexp` will have the regular expression:
```
/.+@.+/ root@localhost
```

And the custom script file `./postfix-config/script.sh` the activation of virtual and virtual-regexp:
```
#!/bin/sh
postconf -e "alias_database = lmdb:/etc/postfix/aliases"
postconf -e "virtual_maps = lmdb:/etc/postfix/virtual, regexp:/etc/postfix/virtual-regexp"
postmap /etc/postfix/virtual
postmap /etc/postfix/virtual-regexp
```

then I do a `docker-compose up -d` on the folder I have my `docker-compose.yml`. 

That's all.

Just one question: Can `mydestination = $myhostname, localhost.$mydomain, localhost.localdomain, localhost` be defined by default, or it's best to have it configurable?
